### PR TITLE
Add support for multiple config files.

### PR DESCRIPTION
**Pull request by ThatJoeMoore**
Since 1.0.0-RC15 (specifically, since arturbosch/detekt@63ea8f6), detekt has support for passing multiple config file paths in `-c`/`--config`, separated by a comma or semicolon. This adds a split -> join to ResolveConfig.kt to resolve each file individually, then put them back together.

If you'd like, I'll add some test for this, but I don't want to make the required changes without getting the go-ahead.,

The need to do actual file resolution complicates the testing of this bit. It seems that the easiest way to test it would be to depend on v0.3.0 of [robstoll/tutteli-spek-extensions](https://github.com/robstoll/tutteli-spek-extensions) (0.3.0 is the last release with support for Spek 1.x) and use that to create/clean up a temporary directory where we can create the files we need. If we want tests but don't want the extra test dependency, we'd need to add essentially a stripped-down version of it to this project.

### CODE REVIEW

**Comment by Ozsie** [comment]
This looks nice, go ahead and add tests if you like.

**Comment by ThatJoeMoore** [comment]
Awesome. I'll get those tests added early next week.

**Comment by ThatJoeMoore** [comment]
Okay, I've now got full tests for everything in ResolveConfig.kt.

To have actual files to resolve, I ended up putting some files in `test/resources`.  Since we never run these tests against a JAR, these should always resolve to actual files - no temp file cleanup necessary!

I'm not certain why the build is failing - it looks like JaCoCo is unhappy about something, but I don't know what it would be. I don't have much experience with JaCoCo.

**Comment by ThatJoeMoore** [comment]
I figured it out.  JaCoCo needed to be updated to run on Java 11, which is what Travis is now using. Also had to fix a bug I introduced into my own tests 🤦‍♂

**Comment by Ozsie** [comment]
Awesome work, thanks :)

**Pull request merged**
