### PR TITLE
Added failBuildOnMaxIssuesReached configuration property

### PR DESCRIPTION
**Pull request by rgrebski**
I have added `failBuildOnMaxIssuesReached` configuration property.
By default set to true.
When set to false it will not fail maven build when max issues were reached

### CODE REVIEW

**Comment by Ozsie** [comment]
Awesome, could you please add tests for the new code to bring coverage back up again?

**Comment by rgrebski** [comment]
Sure thing, just wanted to verify first that you are interested in having such feature at all.
I have added tests plus **couple changes:**

1. Instead of catching `Exception` I now catch `MaxIssuesReached` (otherwise we would  ignore all detekt related errors, not only  reach max issues)
2. I added `detekt-tooling` to dependencies with `provided` scope (it contains MaxIssuesReached exception class)
3. I bumped up version in pom.xml to `1.15.1-SNAPSHOT`

If you would like to change/add/remove anything related to this functionality do not hesitate to share

**Comment by rgrebski** [comment]
Any chance of having this merged soon ?

**Comment by Ozsie** [comment]
Merged and released as 1.15.0.1

**Pull request merged**
